title: "Eli Kishinevsky"
description: "Supply Chain & Business Analytics"
url: "https://elikishinevsky.github.io"
baseurl: ""  # leave blank for user site

# Use Minimal Mistakes (remote theme works on GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Navigation (top menu)
navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Experience"
    url: /experience/
  - title: "Resume"
    url: /resume/
  - title: "Contact"
    url: /contact/

# Author card on homepage
author:
  name: "Eli Kishinevsky"
  avatar: "/assets/images/headshot.jpg"   # add this image later
  bio: "Business Analytics & Supply Chain student. I build communities (Happy Mile Run Club), products (ClubKit), and brands (Combatrium)."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/ekishinevsky"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Ekishinevsky@sandiego.edu"

# Social (optional, for SEO cards)
social:
  name: "Eli Kishinevsky"
  links:
    - "https://linkedin.com/in/ekishinevsky"

# Theme settings
minimal_mistakes_skin: "default"  # try "air", "dark", "neon" later
