title: "Eli Kishinevsky"
description: "Supply Chain & Business Analytics | Entrepreneur"
url: "https://elikishinevsky.github.io"
baseurl: ""
repository: ekishinevsky/elikishinevsky.github.io

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Author card
author:
  name: "Eli Kishinevsky"
  avatar: "/assets/images/headshot.jpg"   # optional, add later
  bio: "I build communities (Happy Mile Run Club), media (Combatrium), and tools (ClubKit)."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/YOUR-LINK"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:YOUR-EMAIL"
