# SITE BASICS
title: "Eli Kishinevsky"
subtitle: "Supply Chain & Business Analytics | Builder of Happy Mile Run Club, Combatrium, ClubKit"
url: "https://elikishinevsky.github.io"
baseurl: ""        # keep empty for user site
repository: ekishinevsky/elikishinevsky.github.io

# THEME
remote_theme: "daattali/beautiful-jekyll@6.0.1"

# NAVBAR (right side)
navbar-links:
  About: "about"
  Projects: "projects"
  Experience: "experience"
  Resume: "assets/resume/Eli_Kishinevsky_Resume.pdf"
  Contact: "contact"

# SOCIAL + AVATAR
author: "Eli Kishinevsky"
avatar: "/assets/img/headshot.jpg"     # upload this file
social-network-links:
  email: "YOUR-EMAIL"
  linkedin: "YOUR-LINKEDIN-HANDLE"     # e.g. elikishinevsky

# APPEARANCE
navbar-col: "#0f172a"      # dark navy
navbar-text-col: "#ffffff"
link-col: "#0ea5e9"        # cyan accent
footer-col: "#0f172a"
footer-text-col: "#94a3b8"
